=== richATavail/Character-to-PNG/config/generatorPlan.dtd
<!--
  ~ generatorPlan.dtd
  ~ Copyright Â© 2018, Richard Arriaga.
  ~ All rights reserved.
-->

<!--
    @author Rich Arriaga
-->
<!ELEMENT selections (target_directory,selection+)>
    <!ELEMENT target_directory (#PCDATA)>
    <!ELEMENT selection
            (selection_name,
                pixel_height,
                pixel_width,
                code_point_ranges,
                colors,
                fonts)>
        <!ELEMENT selection_name (#PCDATA)>
        <!ELEMENT pixel_height (#PCDATA)>
        <!ELEMENT pixel_width (#PCDATA)>
        <!ELEMENT code_point_ranges (range)+>
        <!ELEMENT range (start,end)>
            <!ELEMENT start (#PCDATA)>
            <!ELEMENT end (#PCDATA)>
        <!ELEMENT colors (color|color_name)+>
            <!ELEMENT color_name (#PCDATA)>
            <!ELEMENT color (red,blue,green,alpha)>
                <!ELEMENT red (#PCDATA)>
                <!ELEMENT blue (#PCDATA)>
                <!ELEMENT green (#PCDATA)>
                <!ELEMENT alpha (#PCDATA)>
        <!ELEMENT fonts (font)+>
            <!ELEMENT font (font_style,font_size,font_name)*>
                <!ELEMENT font_name (#PCDATA)>
                <!ELEMENT font_size (#PCDATA)>
                <!ELEMENT font_style (#PCDATA)>

=== richATavail/Character-to-PNG/config/generator_plan.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--
  ~ generatorPlan.xml
  ~ Copyright Â© 2018, Richard Arriaga.
  ~ All rights reserved.
-->

<!--
    @author Rich Arriaga
-->

<!DOCTYPE selections SYSTEM "config/generatorPlan.dtd">
<selections>
   <!-- The base directory to output the png files. -->
    <target_directory>png</target_directory>

    <!-- can define multiple selection elements -->
    <selection>
        <selection_name>example</selection_name>
        <!-- pixel_height & pixel_width are singular and required -->
        <pixel_height>128</pixel_height>
        <pixel_width>128</pixel_width>

        <!-- has a many of character code point range -->
        <code_point_ranges>
            <!-- requires at least one range -->
            <range>
                <start>32</start>
                <end>300</end>
            </range>
            <range>
                <start>340</start>
                <end>400</end>
            </range>
            <range>
                <start>500</start>
                <end>3500</end>
            </range>
        </code_point_ranges>

        <!-- has a many of color/color_name requires at least one;
             a png of each glyph for each color will be generated.
         -->
        <colors>
            <!-- define RGBA -->
            <color>
                <red>45</red>
                <blue>129</blue>
                <green>178</green>
                <alpha>255</alpha>
            </color>

            <!-- provide color name:
                white = (255, 255, 255, 255)
                black = (0, 0, 0, 255)
                red = (255, 0, 0, 255)
                blue = (0, 0, 255, 255)
                green = (0, 255, 0, 255)
                yellow = (255, 255, 0, 255)
                pink = (255, 175, 175, 255)
                orange = (255, 200, 0, 255)
                magenta = (255, 0, 255, 255)
                cyan = (0, 255, 255, 255)
                light gray = (192, 192, 192, 255)
                gray = (128, 128, 128, 255)
                dark gray = (64, 64, 64, 255)
            -->
            <color_name>blue</color_name>
            <color_name>red</color_name>
        </colors>

        <!--
            a many of font that indicates order of generation attempt; the first
            font in the list that has an image for the chosen glyph will be used
        -->
        <fonts>
            <font>
                <!-- fontstyle
                    1: plain
                    2: bold
                    3: italic -->
                <font_style>1</font_style>
                <font_size>100</font_size>
                <font_name>Monaco</font_name>
            </font>
            <font>
                <font_style>2</font_style>
                <font_size>100</font_size>
                <font_name>Times-Roman</font_name>
            </font>
            <font>
                <font_style>3</font_style>
                <font_size>100</font_size>
                <font_name>LucidaSans</font_name>
            </font>
            <font>
                <font_style>1</font_style>
                <font_size>100</font_size>
                <font_name>Georgia</font_name>
            </font>
            <font>
                <font_style>1</font_style>
                <font_size>100</font_size>
                <font_name>Courier</font_name>
            </font>
        </fonts>
    </selection>
</selections>
